<a href="https://colab.research.google.com/github/Err0rGCeni/ICA2022/blob/main/ICA0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# (Pré) Inteligência Computacional

## Imports:

In [1]:
import random
import time
import numpy as np

### Função de Geração de Matrizes


In [2]:
def create_random_matching_matrices(option='random', sizes_to_use=[1, 10], values_to_use=[0, 10]):
  """
    Generate two randomic matrices
    Args:
      option (str):  matrices format

    Returns:
      MA (list), MB (list):
  """
  matrix_a = []
  matrix_b = []
  if option == 'random':
      ra = random.randint(sizes_to_use[0], sizes_to_use[1])
      ca = random.randint(sizes_to_use[0], sizes_to_use[1])
      rb = ca
      cb = random.randint(sizes_to_use[0], sizes_to_use[1])
  elif option == 'square':
      ra = random.randint(sizes_to_use[0], sizes_to_use[1])
      ca = ra
      rb = ca
      cb = rb
  else:
      print("Opção inválida!")
      raise ValueError("Invalid option argument")
  for i in range(ra):
      row = []
      for j in range(ca):
        row.append(random.randint(values_to_use[0],values_to_use[1]))
      matrix_a.append(row)
  for i in range(rb):
      row = []
      for j in range(cb):
        row.append(random.randint(values_to_use[0],values_to_use[1]))
      matrix_b.append(row)
  return matrix_a, matrix_b


In [3]:
matA, matB = create_random_matching_matrices()

In [4]:
print(f"Matriz A {len(matA)}x{len(matA[0])}:", matA)
print(f"Matriz B {len(matB)}x{len(matB[0])}:", matB)

Matriz A 9x6: [[10, 9, 0, 2, 10, 4], [9, 6, 9, 9, 0, 0], [1, 2, 3, 10, 4, 8], [3, 1, 0, 6, 4, 4], [8, 7, 6, 1, 3, 10], [9, 4, 0, 1, 4, 8], [8, 6, 4, 6, 5, 6], [2, 2, 2, 1, 4, 3], [2, 7, 9, 0, 8, 7]]
Matriz B 6x6: [[9, 4, 3, 5, 2, 10], [5, 1, 2, 2, 6, 2], [7, 0, 4, 1, 0, 0], [3, 7, 10, 4, 3, 9], [1, 9, 3, 0, 2, 6], [6, 8, 9, 2, 2, 8]]


## Função para Cálculo de Matrizes: For
Modo clássico de iteração.




In [5]:
def mult_matrices_for(mat_a, mat_b):
  """
    Multiplicate two matrices using for
    Args:
      mat_a (list):  matrix
      mat_b (list):  matrix

    Returns:
      mat_c (list):
  """
  # Amn
  # Bnp
  # Amn * Bnp = Cmp
  try:
    if len(mat_a[0]) != len(mat_b):
      raise ValueError("Matrices don't match!")
  except:
    print("Error with the matrices!")
  time_start =  time.time()
  val_m = len(mat_a)
  val_n = len(mat_b)
  val_p = len(mat_b[0])
  mat_c = []
  # iterate through rows of Mat A
  for m in range(val_m):
    row = []
    # iterate through columns Mat B
    for p in range(val_p):
      # iterate through rows Mat B
      value = 0
      for n in range(val_n):
        value += mat_a[m][n] * mat_b[n][p]
      row.append(value)
    mat_c.append(row)
  time_end = time.time()
  print("Matrix C:\n", mat_c)
  print(f"loop for exec time:: {1000*(time_end - time_start):.4f} ms ")
  return mat_c

In [6]:
matR1 = mult_matrices_for(matA, matB)

Matrix C:
 [[175, 185, 134, 84, 108, 228], [201, 105, 165, 102, 81, 183], [122, 176, 203, 68, 68, 192], [78, 123, 119, 49, 46, 142], [215, 153, 171, 84, 87, 201], [156, 147, 129, 73, 69, 195], [189, 173, 181, 92, 92, 224], [67, 77, 67, 26, 33, 81], [166, 143, 143, 47, 76, 138]]
loop for exec time:: 0.1552 ms 


## Função para Cálculo de Matrizes: Zip
Realiza iterações em paralelo.


In [7]:
def mult_matrices_zip(mat_a, mat_b):
  """
    Multiplicate two matrices using zip
    Args:
      mat_a (list):  matrix
      mat_b (list):  matrix

    Returns:
      mat_c (list):
  """
  # Amn
  # Bnp
  # Amn * Bnp = Cmp
  try:
    if len(mat_a[0]) != len(mat_b):
      raise ValueError("Matrices don't match!")
  except:
    print("Error with the matrices!")
  time_start =  time.time()
  mat_c = [[sum(a * b for a, b in zip(a_row, b_col))
                        for b_col in zip(*mat_b)]
                                for a_row in mat_a]
  time_end =  time.time()
  print("Matrix C:\n", mat_c)
  print(f"loop for exec time:: {1000*(time_end - time_start):.4f} ms ")
  return mat_c

In [8]:
matR2 = mult_matrices_zip(matA, matB)

Matrix C:
 [[175, 185, 134, 84, 108, 228], [201, 105, 165, 102, 81, 183], [122, 176, 203, 68, 68, 192], [78, 123, 119, 49, 46, 142], [215, 153, 171, 84, 87, 201], [156, 147, 129, 73, 69, 195], [189, 173, 181, 92, 92, 224], [67, 77, 67, 26, 33, 81], [166, 143, 143, 47, 76, 138]]
loop for exec time:: 0.1264 ms 


## Função para Cálculo de Matrizes: numpy.dot() vs numpy.matmul()

In [9]:
def mult_matrices_dot(mat_a, mat_b):
  """
    Multiplicate two matrices using numpy.dot
    Args:
      mat_a (list):  matrix
      mat_b (list):  matrix

    Returns:
      mat_c (list):
  """
  # Amn
  # Bnp
  # Amn * Bnp = Cmp
  try:
    if len(mat_a[0]) != len(mat_b):
      raise ValueError("Matrices don't match!")
  except:
    print("Error with the matrices!")
  time_start =  time.time()
  mat_c = np.dot(matA, matB)
  time_end =  time.time()
  print("Matrix C:\n", mat_c)
  print(f"loop for exec time:: {1000*(time_end - time_start):.4f} ms ")
  return mat_c

In [10]:
matR3 = mult_matrices_dot(matA, matB)

Matrix C:
 [[175 185 134  84 108 228]
 [201 105 165 102  81 183]
 [122 176 203  68  68 192]
 [ 78 123 119  49  46 142]
 [215 153 171  84  87 201]
 [156 147 129  73  69 195]
 [189 173 181  92  92 224]
 [ 67  77  67  26  33  81]
 [166 143 143  47  76 138]]
loop for exec time:: 2.2130 ms 


In [11]:
def mult_matrices_matmul(mat_a, mat_b):
  """
    Multiplicate two matrices using numpy.matmul
    Args:
      mat_a (list):  matrix
      mat_b (list):  matrix

    Returns:
      mat_c (list):
  """
  # Amn
  # Bnp
  # Amn * Bnp = Cmp
  try:
    if len(mat_a[0]) != len(mat_b):
      raise ValueError("Matrices don't match!")
  except:
    print("Error with the matrices!")
  time_start =  time.time()
  mat_c = np.matmul(matA, matB)
  time_end =  time.time()
  print("Matrix C:\n", mat_c)
  print(f"loop for exec time:: {1000*(time_end - time_start):.4f} ms ")
  return mat_c

In [12]:
matR3 = mult_matrices_matmul(matA, matB)

Matrix C:
 [[175 185 134  84 108 228]
 [201 105 165 102  81 183]
 [122 176 203  68  68 192]
 [ 78 123 119  49  46 142]
 [215 153 171  84  87 201]
 [156 147 129  73  69 195]
 [189 173 181  92  92 224]
 [ 67  77  67  26  33  81]
 [166 143 143  47  76 138]]
loop for exec time:: 0.2451 ms 


## Comparações com matrizes grandes



In [13]:
bigA, bigB = create_random_matching_matrices("random", [100, 1000], [0, 100])
print(f"Matriz A {len(bigA)}x{len(bigA[0])}:", bigA)
print(f"Matriz B {len(bigB)}x{len(bigB[0])}:", bigB)

Matriz A 279x100: [[19, 36, 28, 37, 81, 82, 7, 7, 93, 13, 40, 100, 2, 75, 30, 71, 74, 97, 72, 65, 59, 86, 26, 26, 49, 15, 15, 43, 78, 60, 91, 88, 64, 30, 29, 1, 58, 59, 37, 50, 18, 95, 29, 37, 43, 49, 43, 13, 80, 87, 24, 6, 24, 32, 56, 63, 98, 30, 58, 56, 21, 93, 77, 52, 42, 18, 98, 85, 19, 98, 80, 26, 38, 4, 34, 16, 8, 90, 27, 81, 45, 2, 21, 50, 41, 83, 48, 40, 26, 49, 42, 87, 73, 96, 37, 98, 12, 7, 21, 78], [22, 60, 51, 89, 81, 58, 44, 34, 35, 92, 61, 85, 86, 28, 23, 40, 75, 72, 76, 43, 33, 83, 74, 57, 60, 60, 2, 85, 10, 2, 87, 25, 68, 83, 37, 21, 52, 25, 83, 4, 100, 0, 7, 15, 65, 57, 7, 79, 17, 22, 59, 84, 99, 61, 65, 63, 60, 43, 28, 43, 16, 20, 66, 99, 5, 77, 50, 53, 9, 40, 0, 85, 32, 25, 35, 27, 75, 48, 72, 48, 21, 13, 19, 42, 58, 79, 72, 13, 16, 67, 73, 48, 11, 24, 28, 29, 28, 34, 72, 97], [1, 47, 67, 38, 30, 75, 18, 63, 72, 17, 93, 8, 58, 93, 96, 93, 47, 67, 50, 89, 38, 16, 88, 15, 0, 42, 25, 21, 41, 58, 34, 6, 9, 49, 67, 83, 37, 96, 13, 98, 22, 0, 25, 58, 84, 49, 28, 29, 20, 85

In [14]:
bigFor = mult_matrices_for(bigA, bigB)
bigZip = mult_matrices_zip(bigA, bigB)
bigDot = mult_matrices_dot(bigA, bigB)
bigMatmul = mult_matrices_matmul(bigA, bigB) 

Matrix C:
 [[250136, 256156, 220766, 268164, 242324, 254596, 267347, 268926, 234003, 217916, 259216, 237647, 241278, 248796, 233067, 233699, 236621, 277805, 222579, 200118, 259908, 258929, 251787, 232187, 271203, 258198, 241336, 243590, 192446, 221018, 234050, 233643, 222388, 221165, 251564, 242529, 211475, 242081, 213340, 234504, 243552, 237762, 221073, 244587, 265984, 243540, 239309, 258465, 276342, 278097, 259614, 240562, 255847, 235318, 251009, 273423, 265171, 246433, 255442, 215446, 243308, 213259, 223489, 240003, 256149, 249179, 243632, 242030, 226511, 275697, 190143, 249050, 257066, 265414, 208419, 228635, 193250, 266100, 241212, 219166, 258012, 235875, 257047, 215771, 263742, 259580, 235295, 239260, 232745, 271597, 249712, 235964, 220620, 241152, 254054, 254451, 224362, 259415, 238413, 242500, 246334, 225998, 267931, 230443, 249484, 256016, 233479, 264652, 242295, 216856, 249841, 270620, 241201, 256131, 235266, 249482, 254945, 227322, 262377, 260113, 222220, 232097, 230525, 216

In [15]:
arrayA = np.array(bigA)
arrayB = np.array(bigB)
bigNumpyDot = mult_matrices_dot(arrayA, arrayB)
bigNumpyMatmul = mult_matrices_matmul(arrayA, arrayB) 

Matrix C:
 [[175 185 134  84 108 228]
 [201 105 165 102  81 183]
 [122 176 203  68  68 192]
 [ 78 123 119  49  46 142]
 [215 153 171  84  87 201]
 [156 147 129  73  69 195]
 [189 173 181  92  92 224]
 [ 67  77  67  26  33  81]
 [166 143 143  47  76 138]]
loop for exec time:: 0.0775 ms 
Matrix C:
 [[175 185 134  84 108 228]
 [201 105 165 102  81 183]
 [122 176 203  68  68 192]
 [ 78 123 119  49  46 142]
 [215 153 171  84  87 201]
 [156 147 129  73  69 195]
 [189 173 181  92  92 224]
 [ 67  77  67  26  33  81]
 [166 143 143  47  76 138]]
loop for exec time:: 0.0784 ms 


Vantagens do NumPy e seus arrays:
- Um **array** é uma coleção de tipos de dados homogêneos que são armazenados em locais de memória contíguos.
  - Uma **list** em Python é uma coleção de tipos de dados heterogêneos armazenados em locais de memória não contíguos.
- O NumPy divide uma tarefa em vários fragmentos e então os processa todos paralelamente.
- O pacote NumPy integra códigos C, C ++ e Fortran em Python. Essas linguagens possuem menos tempo de execução em comparação com Python.

## Links:
https://medium.com/mlearning-ai/introduction-to-numpy-5-extremely-useful-functions-798a65368df
